name: CI - Tests Automatiques

on:
  push:
    branches: [ main, develop, test/* ]
  pull_request:
    branches: [ main ]

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Tester Client Service
        run: |
          cd client-service
          mvn clean test

  test-restaurant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Tester Restaurant Service
        run: |
          cd restaurant-service
          mvn clean test

  test-commande:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Tester Commande Service
        run: |
          cd commande-service
          mvn clean test

  test-livreur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Tester Livreur Service
        run: |
          cd livreur-service
          mvn clean test
